#!/bin/bash
# Simple script to speed up the learning repositories management

export PATH=$PATH:/usr/local/bin

gstatus=`git status --porcelain`

git config --global user.mail "ric.fusari@gmail.com"
git config --global user.email "ric.fusari@gmail.com"

if [ ${#gstatus} -ne 0 ]
then

    git add --all
    git commit -m "Automated sync: $gstatus"
    git pull --rebase
    git push 
fi


git config --global user.mail "s317015@studenti.polito.it"
git config --global user.email "s317015@studenti.polito.it"


