#!/bin/bash
#Script for a fast note capture on the obsidian vault 

# Check if both arguments are provided
if [ $# -ne 1 ]; then
  echo "Usage: $0 <name of the note>"
  exit 1
fi

#Get the name
name=$1

cd /home/riccardo/git/vaults/zettelkasten/fleeting-notes;

touch ${name}.md;

nano ${name}.md;
