#!/bin/bash
# Synchro of my learning repositories

echo ""
echo "Git Sync obsidian"
cd /home/riccardo/git/vaults;
gitsync

echo ""
echo "Git Sync til"
cd /home/riccardo/git/til;
gitsync

echo ""
echo "Git Sync developed code"
cd /home/riccardo/git/devenv;
gitsync